name: Run Postman Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run Postman tests and generate report
        run: |
          mkdir -p test-results/postman
          newman run tests/api-tests/tests.postman_collection.json \
            -e tests/api-tests/tests.postman_environment.json \
            -r cli,html \
            --reporter-html-export test-results/postman/report.html

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: postman-test-results
          path: test-results/postman/
